name: Sync Strava → Notion Leaderboard

on:
  schedule:
    - cron: '0 * * * *'        # every hour
  workflow_dispatch:          # manual “Run workflow” button

jobs:
  sync:
    runs-on: ubuntu-latest

    # ── Inject ALL secrets as environment variables for every step ─────────────
    env:
      STRAVA_CLIENT_ID:     ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
      STRAVA_CLUB_ID:       ${{ secrets.STRAVA_CLUB_ID }}
      NOTION_TOKEN:         ${{ secrets.NOTION_TOKEN }}
      NOTION_DB_ID:         ${{ secrets.NOTION_DB_ID }}
      ACTIVITIES_DB_ID:     ${{ secrets.ACTIVITIES_DB_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Dump env (debug)
        run: |
          echo "STRAVA_CLIENT_ID      = $STRAVA_CLIENT_ID"
          echo "NOTION_DB_ID          = $NOTION_DB_ID"
          echo "ACTIVITIES_DB_ID      = $ACTIVITIES_DB_ID"
          echo "All env vars:"
          env

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run leaderboard sync
        run: python leaderboard.py
